### PR TITLE
Q-Learning Agent plays Frozen Lake

### PR DESCRIPTION
**Pull request by alakh1603**
## Description
I made use of the OpenAI Gym to provide the environment of a simple game called Frozen Lake. Using Q-learning, I then trained an agent to play the game along with the visualization of how the agent does while being trained.
 The motivation is to learn and explore more about machine learning. Reinforcement learning algorithms intrigue me a lot and so I found myself implementing one.

## Affected Dependencies
No changes made.

## How has this been tested?

- The algorithm has been tested on an OpenAI Gym environment(Frozen Lake). 

- Visualizations have been added to see for yourself how the algorithm performs with time.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by ramesht007** [comment]
hey, @AaahAahAha 
Thanks for the PR 
Can you add the description into the code as comment

**Review by ramesht007 — CHANGES_REQUESTED** [review]
Can add comments as I have added for the description.

**Comment by alakh1603** [comment]
I have added the comments as you asked me to.....is it fine now??

**Review by ramesht007 — APPROVED** [review]
Awesome!😀

**Pull request merged**
